[profile.default]
src = "src"
out = "out"
libs = ["lib"]
sender = '0x59e8dc17aed975978c8CCb22Ff69fC8954974359'
gas_reports = ["*"]
# solc = "0.8.19"


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
base = "${BASE_RPC_URL}"
eth = "${ETH_RPC_URL}"
degen = "${DEGEN_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }
base = { key = "${BASE_KEY}" }
eth = { key = "${ETHERSCAN_API_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
